---
# project settings
name: takelage-img-takelbase
version: debian-buster

pipelines:
  - prod

local_user: packer_local

images:
  project:
    target_user: takelwerk
    target_repo: takelbase
    omit_pipeline_name: prod
    layers:
      - site
